name: Frontend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker for Minikube (local)
      - name: Set up Docker for Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker info

      # Build Docker Image
      - name: Build Docker Image for Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA
